name: CI-CD

on:
  push:
    branches: [ main, develop ]
    tags: [ "v*.*.*" ]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
  MODULES: '["user-events-producer","analytics-consumer"]'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(env.MODULES) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - name: Build & test
        run: ./gradlew :${{ matrix.module }}:clean :${{ matrix.module }}:build --no-daemon
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.module }}
          path: ${{ matrix.module }}/build/reports/tests/test

  qodana:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: JetBrains/qodana-action@v2025.2
        with:
          args: "--image jetbrains/qodana-jvm-community:2025.2"
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: .qodana

  image:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(env.MODULES) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4

      - name: Docker login (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: tags
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.REPO }}-${{ matrix.module }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "VERSION=${IMAGE}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "VERSION=${IMAGE}:latest" >> $GITHUB_ENV
          fi
          echo "SHA_TAG=${IMAGE}:sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & push image
        run: |
          if ./gradlew :${{ matrix.module }}:tasks --all | grep -q bootBuildImage; then
            ./gradlew :${{ matrix.module }}:bootBuildImage -PimageName=$SHA_TAG --no-daemon
          else
            ./gradlew :${{ matrix.module }}:build --no-daemon
            docker build -t $SHA_TAG ${{ matrix.module }}
          fi
          docker tag $SHA_TAG $VERSION
          docker push $SHA_TAG
          docker push $VERSION

  deploy:
    runs-on: ubuntu-latest
    needs: image
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy via ssh
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/kafka-lab/docker-compose.yml
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
            cd /opt/kafka-lab
            docker compose pull
            docker compose up -d
            docker system prune -f
          EOF
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
